# Generated by Django 3.0.6 on 2020-10-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quiz/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.AddField(
            model_name='answer',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Animation'),
        ),
    ]
